<a href="https://colab.research.google.com/github/rogerioMB-hub/google_colab/blob/main/Predictions02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import torch
import torch.nn as nn
#import numpy as np
#import matplotlib.pyplot as plt

#01. Criando uma classe para LINEAR REGRESSION (LR)

In [18]:
class LinearRegression(torch.nn.Module):
  def __init__(self, input_dim, output_dim):              #inicializador/construtor de instancias
    super(LinearRegression, self).__init__()
    self.linear = torch.nn.Linear(input_dim, output_dim)  #função linear com pesos(w) e bias(b) aleatórios

  def forward(self, x):
    pred = self.linear(x)
    return pred

In [19]:
  torch.manual_seed(1)
  model1 = LinearRegression(1, 1)     # criando um objeto model1
  print(list(model1.parameters()))    # imprimindo seus parametros em forma de lista para melhor visualização

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [20]:
x = torch.tensor([1.0])
print(model1.forward(x))


tensor([0.0739], grad_fn=<ViewBackward0>)


In [21]:
x = torch.tensor([[1.0],[2.0],[3.3],[5.8]])  # preds para variaveis diversas
print(model1.forward(x))


tensor([[0.0739],
        [0.5891],
        [1.2590],
        [2.5471]], grad_fn=<AddmmBackward0>)
