<a href="https://colab.research.google.com/github/rogerioMB-hub/google_colab/blob/main/Predictions01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch


# 01. Realizando uma predição/projeção no modelo definido por y

In [2]:
w = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)


In [3]:
def forward(x):
    y = w * x + b
    return y

In [5]:
x = torch.tensor(4.0) # entrando com o valor 4.0 para x, obtém-se na sequencia o respectivo valor para y
y = forward(x)
print(y)

tensor(13., grad_fn=<AddBackward0>)


In [6]:
x = torch.tensor([[4.0], [5.0]]) # entrando com os dados 4.0 e 5.0, obtém-se os respectivos valores para a função
y = forward(x)
print(y)

tensor([[13.],
        [16.]], grad_fn=<AddBackward0>)


# 02. Criando uma classe LINEAR

In [7]:
from torch.nn import Linear

In [8]:
torch.manual_seed(1)  # gerando uma semente para construção de numeros aleatórios

In [11]:
model = Linear(in_features=1, out_features=1) # cria um modelo linear com 1 parametro de entrada e 1 de saída.
print(model.weight)   # w é gerado aleatoriamente
print(model.bias)     # b é gerado aleatoriamente

Parameter containing:
tensor([[-0.1939]], requires_grad=True)
Parameter containing:
tensor([0.4694], requires_grad=True)


In [14]:
x = torch.tensor([[2.0],[3.3]]) # para cada entrada, uma predição: aqui são duas entradas ...
y = model(x)
print(y)

tensor([[ 0.0816],
        [-0.1704]], grad_fn=<AddmmBackward0>)
