<a href="https://colab.research.google.com/github/rogerioMB-hub/google_colab/blob/main/Tensores05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors: matrix product

In [7]:
import torch

Creating tensors a and b

In [8]:
t_a = torch.tensor([0,3,5,5,5,2]).view(2,3)
t_b = torch.tensor([3,4,3,-2,4,-2]).view(3,2)
print(t_a)
print(t_b)

tensor([[0, 3, 5],
        [5, 5, 2]])
tensor([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])


Three diferent ways of multiplication

In [9]:
t_result = torch.mm(t_a,t_b)
print(t_result)

tensor([[ 29, -16],
        [ 38,   6]])


In [10]:
t_result = torch.matmul(t_a,t_b)
print(t_result)


tensor([[ 29, -16],
        [ 38,   6]])


In [11]:
t_result = t_a @ t_b
print(t_result)

tensor([[ 29, -16],
        [ 38,   6]])
