<a href="https://colab.research.google.com/github/rogerioMB-hub/google_colab/blob/main/Tensores01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the Pytorch

In [18]:
import torch

Creating a tensor v

In [19]:
v = torch.tensor([1, 2, 3, 4, 5, 6])
print(v[0])


tensor(1)


In [13]:
print(v[2:])


tensor([3, 4, 5, 6])


Creating a float type tensor f

In [15]:
f = torch.FloatTensor([1, 2, 3, 4, 5, 6])
print(f.dtype)
print(f.size() )

torch.float32
torch.Size([6])


Viewing and rashapping a tensor

In [16]:
v.view(6, 1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [17]:
v.view(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])