<a href="https://colab.research.google.com/github/rogerioMB-hub/google_colab/blob/main/Tensores04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

tensors' study: 4th part
# Tensor view and slicing

In [5]:
import torch
import matplotlib.pyplot as plt

t_one = torch.arange(10)
t_two = torch.arange(10).view(10,1)
print(t_one)
print(t_two)
print(t_one.size())
print(t_two.size())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
torch.Size([10])
torch.Size([10, 1])


In [7]:
t_three = torch.arange(27).view(3,3,3)
print(t_three)
print(t_three.size())

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])
torch.Size([3, 3, 3])


In [8]:
slice_t_three = t_three[1, :, :]
print(slice_t_three)

tensor([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])


In [9]:
slice_t_three = t_three[1, 1, :]
print(slice_t_three)

tensor([12, 13, 14])


In [10]:
slice_t_three = t_three[1, :, 2]
print(slice_t_three)

tensor([11, 14, 17])
